spring:
  profiles:
    group:
      production:
        - production1
        - production2
      local:
        - local1
        - local2
    #JVM 옵션을 설정(-Dspring.profiles.active=local)할경우 application.yml의 active profile 설정은 무시됨. (우선순위)
    active: production
---
spring.config.activate.on-profile: local
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - shutdown
---
spring.config.activate.on-profile: production
test: value
commontest: 3
management:
  endpoint:
    shutdown:
      enabled: false
---
spring.config.activate.on-profile: production2
test2: value2
commontest: 2
---
spring.config.activate.on-profile: production1
test1: value1
#yml document의 순서에 따라 commontest의 값이 덮어 씌워지니 주의 할것.
commontest: 1
---
